apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: eu.gcr.io/ticketing-dev-297508/auth
      context: auth
      sync:
        infer:
          - 'src/**/*.ts'
    - image: eu.gcr.io/ticketing-dev-297508/client
      context: client
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: { projectId: eu.gcr.io/ticketing-dev-297508/auth }
      artifacts:
        - image: eu.gcr.io/ticketing-dev-297508/auth
          context: auth
          docker:
            dockerfile: Dockerfile
          sync:
            infer:
              - 'src/**/*.ts'
